In [1]:
import torch

In [2]:
a = torch.randn(2, 3)  # 2 rows, 3 columns
print(a)
print(a.shape, a.shape[0], a.shape[1], a.dim())
print(a.type())
print(isinstance(a, torch.FloatTensor))

tensor([[ 0.5555, -0.8546,  0.1496],
        [-1.3402,  0.8476,  1.1632]])
torch.Size([2, 3]) 2 3 2
torch.FloatTensor
True


In [3]:
print(torch.cuda.is_available(),  # CUDA
      torch.backends.mps.is_available(),  # multi-process service
      torch.backends.cudnn.is_available())  # CUDA deep neural network

False True False


In [4]:
import numpy as np

b = torch.tensor([1.1])

print(b.shape)
print(b.type())

data = np.ones(2)
print(data)

torch.from_numpy(data)  # numpy to tensor

torch.Size([1])
torch.FloatTensor
[1. 1.]


tensor([1., 1.], dtype=torch.float64)

In [5]:
c = torch.ones(2)

print(c.shape)
print(c)
print(c.numel(), c.dim())

torch.Size([2])
tensor([1., 1.])
2 1


In [6]:
torch.set_default_tensor_type(torch.DoubleTensor)  # set default tensor type

/Users/yuzheyang/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/__init__.py:613: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1692171543885/work/torch/csrc/tensor/python_tensor.cpp:453.)
  _C._set_default_tensor_type(t)


In [7]:
torch.full([2, 3], 7)  # full tensor

tensor([[7, 7, 7],
        [7, 7, 7]])

In [8]:
# torch unsqueeze